---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tff-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tff
      version: prod
  minReadySeconds: 2 #minimum delay for a pod to be considered available
  strategy:
    type: RollingUpdate #zero downtime updating ofpods with new ones
    rollingUpdate:
      maxUnavailable: 1 #maximum unavailable Pods during update process
      maxSurge: 1 #maximum pods that can be created over the desired number
  template:
    metadata:
      labels:
        app: tff
        version: prod
    spec:
      containers:
      - name: tff-webdev
        image: pierremagain/tff_image:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: tff-svc
  labels:
    app: tff
    version: prod
spec:
  type: NodePort
  ports:
    - port: 80 # internal cluster port
      nodePort: 30005 # external cluster port
      protocol: TCP
  selector:
    app: tff
    version: prod
