name: Docker CI

on:
  push:
    paths:
      - 'test/**' # Déclenche le workflow sur les pushs vers la branche main

jobs:
  docker_build:
    runs-on: self-hosted  # Exécuter sur le runner auto-hébergé
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: docker image build -t pierremagain/test:latest .

  docker_push:
    runs-on: self-hosted  # Exécuter sur le runner auto-hébergé
    needs: docker_build  # Le job 'docker_push' attend la fin du job 'docker_build'
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Push Docker image
        run: docker push pierremagain/test:latest
