name: Provision Infrastructure

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: self-hosted  # Ou ubuntu-latest si vous utilisez un runner GitHub hébergé

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform get
        run: terraform get

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve -lock=false
